example/package-lock.json
example/package.json
example/src/config.json
example/src/index.ts
package.json
src/client/StreamOpts.ts
src/media/H264NalSplitter.ts
src/media/streamLivestreamVideo.ts

- improve method for finding emulation prevention bytes
- don't remove emulation prevention bytes from all nal units, just the important ones, to improve performance
- change name for hardware acceleration since it is not "hardware encoding"

Small fixes

---

src/media/H264NalSplitter.ts

Profiling the library showed that `parseNal` is very inefficient. It was performing an `O(n^2)` search for the NAL start prefix code, and also doing a lot of allocations in the for loop. All of that in a very hot code path leads to poor performance.
I rewritten the function to use `indexOf`, and get rid of the `O(n^2)` loop along with the excessive allocation from the `subarray()` call.
<details>
<summary>Before</summary>
```
Statistical profiling result from isolate-0x5c006f0-186514-v8.log, (47617 ticks, 29409 unaccounted, 0 excluded).
[Shared libraries]:
ticks  total  nonlib   name
558    1.2%          /usr/lib/x86_64-linux-gnu/libc.so.6
31    0.1%          /home/hp/.local/bin/node
27    0.1%          /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.30
9    0.0%          [vdso]
[JavaScript]: …
```

Optimize `parseNal`

---

package.json
src/client/packet/AudioPacketizer.ts
src/client/packet/BaseMediaPacketizer.ts
src/client/packet/VideoPacketizerH264.ts
src/client/packet/VideoPacketizerVP8.ts
src/client/voice/BaseMediaConnection.ts
src/client/voice/MediaUdp.ts

This is still very WIP, missing a few pieces and having some problems that I haven't root caused yet. However it's in a good enough state that other people can test and improve on.
Note: The current implementation timestamps the packet when `sendFrame()` is called. If there are extra processing steps before it that causes the audio and video streams to go out of sync, this will not fix it.
TODO:
- When the SSRC is changed, the total packet count and total octet count should be reset
- Does the SSRC actually change in the middle of a stream?
- Since we're using the SSRC in 2 places now, there should be a local SSRC variable in `BaseMediaPacketizer` to prevent "prop drilling"
- After some amount of time, Discord decided to just stop receiving/decoding audio. The audio codec field in the RTC …

RTCP Sender Report

---

src/media/H264NalSplitter.ts

This is probably stepping into the realm of micro-optimizations, and only matters to the slowest of computers, but I'll take any opportunity to optimize :)
I forgot to commit the changes separately, so the first commit is a bit huge, but here's a rundown of all the changes
- Rewritten `rbsp` to use `indexOf` and `copy`
- A better way to search for NAL start codes that only uses 1 `indexOf` call
- Rewritten chunking loop to only scan each data chunk exactly once

Optimize `H264NalSplitter` more

---

src/media/AudioStream.ts
src/media/VideoStream.ts

For true real-time sources (RTSP/RTMP/SRT livestreams), sleeping is not recommended, since it prevents ffmpeg from "catching up" with the livestream, and can cause packet loss from the input side if a UDP-based protocol is used.
This PR adds a parameter to allow disabling the sleeping behavior.

Allow disabling sleep in process streams

---

src/client/packet/VideoPacketizerAnnexB.ts
src/client/processing/AnnexBNalSplitter.ts

Instead of packing the NAL units into frames before sending to the packetizer, now we send the NAL units itself, including the AUD to the packetizer, and then set the marker bit on the AUD instead. This saves an allocation every frame.
With this change, the `sendFrame` function no longer receives individual frames, but individual NAL units instead. We can either do nothing, or rename it into something more appropriate. New naming welcome.

Remove the NALU packing hack

---

package.json

Closes #68
Updating `discord.js-selfbot-v13` to `3.x` since TypeScript screams at me non-stop.
Also, due to https://github.com/dank074/Discord-video-stream/issues/58, I've made `@discordjs/opus` an optional dependency, and added `opusscript` as a fallback. That way on machines that fail to build `@discordjs/opus`, there'll be a WASM option available.

Update deps, move `@discordjs/opus` to optional deps

---

package.json
src/media/streamLivestreamVideo.ts

This is an implementation of my suggestion in https://github.com/dank074/Discord-video-stream/issues/88#issuecomment-2074024524
Usage:
```javascript
let playback;
try {
playback = streamLivestreamVideo(...);
await playback;
}
catch (e)
{
if (playback.isCanceled)
// do stuff when cancel
// do stuff when error
}
// somewhere else
playback?.cancel();
```

Use `p-cancelable`

---

package.json
src/media/AudioStream.ts
src/media/BaseMediaStream.ts
src/media/LibavDemuxer.ts
src/media/VideoStream.ts
src/media/streamLivestreamVideo.ts

Turns out relying on `-re` to provide periodic frame output is wrong, as I learned [the hard way](https://github.com/dank074/Discord-video-stream/issues/115#issuecomment-2493270004). This PR reintroduces the sleeping code for periodic frame output, which also involves getting backpressure to work so that memory leaks don't happen.
The mechanism for this is pretty simple. Frames are repeatedly extracted from the input stream until either the video or audio pipe reaches `highWaterMark`, after which we pause the input stream. When the pipe has been drained, we resume the input stream and continue extraction.
Unfortunately, this only partially fixes #115, something in the video file is causing consistent 5+ seconds pauses, that doesn't happen with other files that I've tested. Will continue …

Bring back sleeping code for periodic frame timing

---

src/media/BaseMediaStream.ts
src/media/LibavDemuxer.ts

No need to have extra buffering on `BaseMediaStream`, so `highWaterMark` is set to 0 there. I also re-enabled multi-threading after figuring out what went wrong last time.

Tweak `highWaterMark`, re-enable LibAV multithreading

---

src/media/streamLivestreamVideo.ts

When killing the ffmpeg process I was getting the following exception:
```
TypeError: Cannot read properties of undefined (reading 'get') at endCB fluent-ffmpeg\lib\processor.js:543:37)
```
It seems to be a fluent-ffmpeg bug: https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/issues/861
It stopped throwing the exception when I moved the `.output` line in the ffmpeg command builder after the lines attaching event listeners with `.on`

prevent fluent-ffmpeg exception when killing process

---

src/media/newApi.ts

When using `playStream` in a playlist loop, the `vStream.once("finish")` callback in its current implementation does not provide a mechanism to await the completion of a video before proceeding to the next one. As a result, all videos in the playlist attempt to play simultaneously.
* [`src/media/newApi.ts`](diffhunk://#diff-a520dddc64ccaf64af3f7c950f3514931c0413b12fa61a49fc3adbbe5e35751cR393-R399): Added a promise to the `playStream` function that resolves when the stream finishes.
Usage example:
```typescript
const client = new Client();
const streamer = new Streamer(client);
let current: ReturnType<typeof NewApi.prepareStream>["command"];
client.on("ready", async () => {
console.log("Ready");
await streamer.joinVoice(config.guildId, config.channelId);
if …
```

Return a promise on stream finish to improve async handling in playStream function

---

src/media/LibavDemuxer.ts

On very bad sources (for example live streams over bad connection), there can be scenarios where one stream is completely full, while the other is completely empty, which causes the full stream to wait forever for the empty stream, which will never receive a frame. I haven't thought of a good solution for this yet, so for now, increase both stream's buffer size to 128 frames.

Increase audio and video stream buffer size to 128 frames

---

src/media/streamLivestreamVideo.ts

There are other reasons not listed here (stream options being thrown everywhere, leakage of internal library classes), but this should be good enough for now. Do we need a runtime warning though?

Deprecate the old API

---

src/media/LibavDemuxer.ts

Demuxing probably doesn't use multiple threads anyway, and it might compete for threads with other stuff, namely encryption
cc @uwuv3, try the release published here

Disable LibAV multithreading, again

---

package.json
pnpm-lock.yaml
src/media/newApi.ts

Adding this because while working on https://github.com/Discord-RE/FFmpeg-input-premade, I came across some cases where ending the stream is a bit more complicated than just a single `command.kill`, and having a unified way to end processes would be better for other users.
`AbortSignal` is chosen because many other Node APIs and libraries are using it as the way to abort processes.
```javascript
// Global variable
let controller = new AbortController();
const { command, output } = prepareStream(url, { ... }, controller.signal);
await playStream(output, streamer, { ... }, controller.signal);
// End everything
controller.abort();
```

Add `AbortSignal` to `prepareStream` and `playStream`

---

package.json
pnpm-lock.yaml
src/client/Streamer.ts
src/media/BaseMediaStream.ts
src/media/LibavDecoder.ts
src/media/LibavDemuxer.ts
src/media/LibavInstance.ts
src/media/newApi.ts
src/media/utils.ts

Only took 2 months since #133 was made...
Should keyframe extraction be in this repo though, or it should be in https://github.com/Discord-RE/FFmpeg-input-premade?

Stream preview

---

src/media/BaseMediaStream.ts
src/media/LibavDemuxer.ts
src/media/newApi.ts

This rewrites the syncing logic to be more in-line with how media players do syncing. The audio stream is played at a regular cadence, while the video stream will drop/repeat frames to stay in sync with the audio. When adapted to this use case, it results in the video stream either not sleeping ("dropping frames") or sleep for an extra frame ("repeating frames").
All these changes together allow me to get <0.5s latency, timed by sending a volume adjust command and timing the delay between the bot's response and the audio adjusting (not scientific but it's a lot better than before). Badly behaving streams will still have a delay, because of more buffering required for proper syncing.

Rewrite stream sync mechanism + high water mark tweak

---

biome.json
package.json
pnpm-lock.yaml
src/client/encryptor/TransportEncryptor.ts
src/client/packet/BaseMediaPacketizer.ts
src/client/packet/VideoPacketizerAnnexB.ts
src/client/processing/AnnexBHelper.ts
src/media/LibavDemuxer.ts
src/media/newApi.ts
src/utils.ts

`nut` is a [very simple generic container format](https://ffmpeg.org/nut.html), probably a good idea to use this instead of the more complex `matroska` for interprocess purposes
This will be a breaking change for people using `playStream` with their custom streams. They'll need to change their output format to `nut`, or specify `format: "matroska"` in the `playStream` option

Use `nut` as a transport format

---

src/media/LibavDecoder.ts
src/media/newApi.ts
src/utils.ts

Deno and Bun doesn't support the `zeromq` package yet. Until support is added (or maybe until Bun does its own thing and integrates the library into the runtime), disable the feature on those runtimes. Also added an override flag for decoder initialization for easy testing.

Disable the volume control on Deno and Bun due to ZeroMQ dependency
